### ISSUE TITLE
Provide some way for numba to be disabled - coverage

### ISSUE THREAD

**Issue by benjeffery** [jeromekelleher/phylokit#11]
`numba` JIT'd functions do not yet report coverage (see https://github.com/numba/numba/issues/4268) we can get around this by disabling numba when running the coverage tests.

**Comment by jeromekelleher** [comment]
Sounds like we do need a custom decorator and a conditional numba import depending on a module-level flag?

**Comment by benjeffery** [comment]
Yes, module level flag on the public API, that is then set by a `pytest` flag, similar to `--skip-slow` over at `tskit`.

**Comment by benjeffery** [comment]
Closed by #12
