### ISSUE TITLE
Update existing functions to use dataset interface

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/phylokit#14]
#13 added the initial work for using the proposed xarray based interface. To close this issue we need to:

1. Change the signature of existing functions to use ``ds`` rather than ``tree``, and use (e.g.) ``ds.node_parent.data`` instead of ``tree.parent_array`` when passing the arrays to the jitted functions.
2. Update tests to convert tskit trees using ``pk.from_tskit(tree)``, rather than passing the tree directly. 
3. Check that there are no major performance drops involved in doing this 

Doing (2) might involve reimplementing a few functions from tskit. We can use ``-1`` instead of ``tree.virtual_root``.

cc @Billyzhang1229

**Comment by Billyzhang1229** [comment]
@jeromekelleher maybe we could close this issue now.
