### ISSUE TITLE
Add tree visualize function

### ISSUE THREAD

**Issue by Billyzhang1229** [jeromekelleher/phylokit#29]
We could use [igraph](https://igraph.org/python/) combine with [ploty](https://plotly.com/) to visualize our tree.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/35052899/182369575-9273e4ca-18a4-4a9c-bebe-92719840525b.png">

A [simple tutorial ](https://plotly.com/python/tree-plots/) here is provided by `plotly`.

**Comment by jeromekelleher** [comment]
Cool! Do you have some basic code for what we would need to do?

**Comment by Billyzhang1229** [comment]
> Cool! Do you have some basic code for what we would need to do?

Need to go to [this link](https://github.dev/jeromekelleher/phylokit/blob/675b5ed00c0aa6bcc7b53227140ec570191a4e97/examples/tree_vis.ipynb) to actually see how it shows like.

**Comment by jeromekelleher** [comment]
Hmm - so we're still doing a fair bit of work in computing the layout though, right?

**Comment by Billyzhang1229** [comment]
Issue closed

 -  See #31 for more details.
